databases:
  db1:
      dsn: postgresql://postgres_exporter:61cf6cbcfb47e37e5d6cf0c67cbf05d0af845450c5ce7c8d11b85d6d591e3b252cceace381a2db7b@1:5432/postgres?sslmode=disable      

metrics:
  pg_table_vacuum:
    type: counter
    description: Number of times this table has been manually vacuumed (not counting VACUUM FULL)
    labels: [relname]
  pg_table_autovacuum:
    type: counter
    description: Number of times this table has been vacuumed by the autovacuum daemon
    labels: [relname]
  pg_table_analyze:
    type: counter
    description: Number of times this table has been manually analyzed
    labels: [relname]
  pg_table_autoanalyze:
    type: counter
    description: Number of times this table has been analyzed by the autovacuum daemon

queries:
  process_stats:
    databases: [db1]
    metrics:
      - pg_process
    sql: >
      SELECT
        state,
        COUNT(*) AS pg_process
      FROM pg_stat_activity
      WHERE state IS NOT NULL
      GROUP BY state

  table_stats:
    databases: [db1]
    metrics:
      - pg_table_vacuum
      - pg_table_autovacuum
      - pg_table_analyze
      - pg_table_autoanalyze
    sql: >
      SELECT
        relname,
        vacuum_count AS pg_table_vacuum,
        autovacuum_count AS pg_table_autovacuum,
        analyze_count AS pg_table_analyze,
        autoanalyze_count AS pg_table_autoanalyze
      FROM pg_stat_user_tables